# These are supported funding model platforms

github: [ibarraespinosa] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buymeacoffee: https://www.buymeacoffee.com/ibarraespinosa # Replace with a single Patreon username
liberapay: ibarraespinosa # Replace with a single Liberapay username
